# Generated by Django 4.0.4 on 2022-05-19 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Хобби',
                'verbose_name_plural': 'Хобби',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125, verbose_name='логин')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('birth_date', models.DateField(blank=True, verbose_name='дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='еmail адрес')),
                ('phone', models.CharField(blank=True, max_length=125, verbose_name='номер телефона')),
                ('avatar', models.ImageField(blank=True, help_text='Формат: jpg, gif, png.<br> Макс. размер файла: 2Mb.<br> Рекомендуется: 512x512px.', upload_to='avatars/', verbose_name='фотография')),
                ('status', models.CharField(blank=True, max_length=125, verbose_name='статус')),
                ('hobby', models.ManyToManyField(related_name='%(class)s', to='accounts.hobby', verbose_name='хобби')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125, verbose_name='логин')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('birth_date', models.DateField(blank=True, verbose_name='дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='еmail адрес')),
                ('phone', models.CharField(blank=True, max_length=125, verbose_name='номер телефона')),
                ('avatar', models.ImageField(blank=True, help_text='Формат: jpg, gif, png.<br> Макс. размер файла: 2Mb.<br> Рекомендуется: 512x512px.', upload_to='avatars/', verbose_name='фотография')),
                ('hobby', models.ManyToManyField(related_name='%(class)s', to='accounts.hobby', verbose_name='хобби')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Арендодатель',
                'verbose_name_plural': 'Арендодатели',
                'abstract': False,
            },
        ),
    ]
