# Generated by Django 4.0.4 on 2022-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='адрес объекта аренды')),
                ('rooms', models.PositiveIntegerField(verbose_name='количество комнат')),
                ('conditions', models.CharField(max_length=255, verbose_name='бытовые условия')),
                ('duration', models.PositiveIntegerField(verbose_name='срок сдачи')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='дата подачи')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
